Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2018-10, with the labels that each got.

#369 fix ProxyManager proxies map
  src/proxy/ProxyManager.ts
  test/ClientProxyTest.js
Labels: Type: Defect

#368 add AddressHelper object and refactor the connection behavior
  src/Util.ts
  src/discovery/HazelcastCloudDiscovery.ts
  src/invocation/ClusterService.ts
  test/AddressHelperTest.js
  test/config/ConfigBuilderTest.js
Labels: Type: Enhancement

#346 add documentation for Node.js Client API Overview and some data struc…
  README.md
Labels: Type: Documentation

#343 add documentatition for Setting Up Client Network Chapter
  README.md
Labels: Type: Documentation

#349 Adds getting started in Readme.MD
  README.md
Labels: Type: Documentation

#344 add documentation for Securing Client Connection chapter
  README.md
Labels: Type: Documentation

#359 add documentation for Distributed Events
  README.md
Labels: Type: Documentation

#372 fix Client API get functions
  code_samples/distributed_object_listener.js
  src/HazelcastClient.ts
  src/proxy/ProxyManager.ts
  src/proxy/topic/ReliableTopicProxy.ts
  test/ClientProxyTest.js
  test/ClientReconnectTest.js
  test/HazelcastClientTest.js
  test/ListenerServiceTest.js
  test/ListenersOnReconnectTest.js
  test/atomiclong/AtomicLongTest.js
  test/flakeid/FlakeIdGeneratorOutOfRangeTest.js
  test/flakeid/FlakeIdGeneratorProxyTest.js
  test/list/ListProxyTest.js
  test/lock/LockProxyTest.js
  test/map/MapAggregatorsDoubleTest.js
  test/map/MapAggregatorsIntTest.js
  test/map/MapAggregatorsLongTest.js
  test/map/MapEntryProcessorTest.js
  test/map/MapPartitionAwareTest.js
  test/map/MapPredicateTest.js
  test/map/MapProxyTest.js
  test/map/MapStoreTest.js
  test/map/NearCachedMapStressTest.js
  test/map/NearCachedMapTest.js
  test/multimap/MultiMapProxyListenersTest.js
  test/multimap/MultiMapProxyLockTest.js
  test/multimap/MultiMapProxyTest.js
  test/nearcache/InvalidationMetadataDistortionTest.js
  test/nearcache/LostInvalidationsTest.js
  test/nearcache/MigratedDataTest.js
  test/nearcache/NearCacheSimpleInvalidationTest.js
  test/pncounter/PNCounterBasicTest.js
  test/pncounter/PNCounterConsistencyTest.js
  test/pncounter/PNCounterWithLiteMembersTest.js
  test/queue/QueueProxyTest.js
  test/replicatedmap/ReplicatedMapProxyTest.js
  test/ringbuffer/RingbufferTest.js
  test/semaphore/SemaphoreProxyTest.js
  test/serialization/DefaultSerializersLiveTest.js
  test/serialization/PortableSerializersLiveTest.js
  test/set/SetProxyTest.js
  test/ssl/ClientSSLTest.js
  test/statistics/StatisticsTest.js
  test/topic/TopicTest.js
Labels: Type: Defect

#374 fix code samples' get functions
  code_samples/aggregation.js
  code_samples/custom_serializer.js
  code_samples/flakeid_generator.js
  code_samples/global_serializer.js
  code_samples/hazelcast_cloud_discovery.js
  code_samples/lifecycle_listener.js
  code_samples/list.js
  code_samples/map.js
  code_samples/map_entry_listener.js
  code_samples/near_cache.js
  code_samples/org-website/AtomicLongSample.js
  code_samples/org-website/EntryProcessorSample.js
  code_samples/org-website/ListSample.js
  code_samples/org-website/LockSample.js
  code_samples/org-website/MapSample.js
  code_samples/org-website/MultiMapSample.js
  code_samples/org-website/QuerySample.js
  code_samples/org-website/QueueSample.js
  code_samples/org-website/ReliableTopicSample.js
  code_samples/org-website/ReplicatedMapSample.js
  code_samples/org-website/RingBufferSample.js
  code_samples/org-website/SetSample.js
  code_samples/paging_predicate.js
  code_samples/pn_counter.js
  code_samples/queue.js
  code_samples/set.js
Labels: Type: Defect

#375 make ConfigBuilder accessible by user
  src/index.ts
  test/config/ConfigBuilderHazelcastCloudTest.js
  test/config/ConfigBuilderSSLTest.js
  test/config/ConfigBuilderTest.js
  test/config/ConfigLocationTest.js
Labels: Type: Enhancement

#341 add documentation for serialization content and IdentifiedDataSeriali…
  README.md
Labels: Type: Documentation, Type: Enhancement

#377 fix portable factory declarative configuration
  src/serialization/portable/PortableSerializer.ts
  test/serialization/config/Address.js
  test/serialization/config/FactoriesTest.js
  test/serialization/config/Foo.js
  test/serialization/config/hazelcast-client.json
Labels: Type: Defect

#353 Adds Development and Testing section
  README.md
Labels: Type: Documentation

#385 swap getting started and features chapters
  README.md
Labels: Type: Enhancement

#382 add documentation for client operation modes
  README.md
Labels: Type: Documentation

#373 index all topics as in the documentation issue
  README.md
Labels: Type: Documentation

#386 Adding the support/license related content and some minor improvements.
  README.md
Labels: Type: Documentation

#387 Adds missing items in features list
  README.md
Labels: Type: Enhancement

#379 add documentation for distributed query and using predicates
  README.md
Labels: Type: Documentation

#388 refactor Hazelcast Node.js Client to Hazelcast Node.js client
  README.md
Labels: Type: Documentation

#384 add EntryProcessor documentation
  README.md
Labels: Type: Documentation, Type: Enhancement

#390 some fixes on documentation
  README.md
  code_samples/org-website/GlobalSerializerSample.js
Labels: Type: Documentation

#378 add usages of data structures to documentation
  README.md
Labels: Type: Documentation

#391 add fast-aggregations documentation
  README.md
Labels: Type: Documentation
