Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2018-12, with the labels that each got.

#432 Give reference to Near Cache in Using Map section
  README.md
Labels: Type: Enhancement

#352 add default and sample configuration files
  hazelcast-client-default.json
  hazelcast-client-sample.json
Labels: Type: Enhancement

#438 Fix for statistics test failure
  src/HazelcastClient.ts
  src/PartitionService.ts
  src/invocation/ClusterService.ts
  src/statistics/Statistics.ts
  test/ClusterServiceTest.js
  test/LoggingTest.js
  test/LostConnectionTest.js
  test/MembershipListenerTest.js
  test/declarative_config/ConfigLocationTest.js
  test/semaphore/SemaphoreProxyTest.js
  test/serialization/config/CustomSerializerTest.js
  test/serialization/config/FactoriesTest.js
  test/serialization/config/customserializer.json
  test/ssl/ClientSSLTest.js
  test/statistics/StatisticsTest.js
Labels: Type: Test-Failure

#436 Fixes ssl configuration in README according to recent changes
  README.md
  src/config/Config.ts
Labels: Type: Documentation

#442 Update table of contents
  README.md
Labels: Type: Defect

#444 Client stats code sample
  code_samples/client_statistics.js
Labels: Type: Documentation
