Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2018-08, with the labels that each got.

#316 remove redundant methods from vector clock
  src/core/VectorClock.ts
Labels: Type: Cleanup

#324 Fix typing of `hazelcast.logging` property in HazelcastClient
  src/HazelcastClient.ts
  src/config/Properties.ts
Labels: Type: Defect

#326 fix on HazelcastClientTest
  test/HazelcastClientTest.js
Labels: Type: Test-Failure

#328 update windows batch script
  scripts/download-rc.bat
Labels: Type: Enhancement

#329 fix on ListenersOnReconnectTest
  test/ListenersOnReconnectTest.js
Labels: Type: Enhancement

#330 add typedef rule to tslint
  src/BitsUtil.ts
  src/ClientMessage.ts
  src/HazelcastClient.ts
  src/HeartbeatService.ts
  src/ListenerService.ts
  src/PartitionService.ts
  src/Util.ts
  src/aggregation/Aggregator.ts
  src/config/ConfigBuilder.ts
  src/config/ListenerConfig.ts
  src/core/Member.ts
  src/core/Predicate.ts
  src/core/UUID.ts
  src/invocation/ClientConnection.ts
  src/invocation/ClientConnectionManager.ts
  src/invocation/ClusterService.ts
  src/invocation/InvocationService.ts
  src/invocation/RegistrationKey.ts
  src/logging/DefaultLogger.ts
  src/logging/LoggingService.ts
  src/logging/NoLogger.ts
  src/nearcache/DataRecord.ts
  src/nearcache/MetadataContainer.ts
  src/nearcache/NearCache.ts
  src/nearcache/RepairingHandler.ts
  src/proxy/BaseProxy.ts
  src/proxy/LockProxy.ts
  src/proxy/MapProxy.ts
  src/proxy/MultiMapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  src/proxy/ProxyManager.ts
  src/proxy/QueueProxy.ts
  src/proxy/ReplicatedMapProxy.ts
  src/proxy/topic/ReliableTopicProxy.ts
  src/serialization/DefaultPredicates.ts
  src/serialization/ObjectData.ts
  src/serialization/SerializationService.ts
  src/serialization/SerializationUtil.ts
  src/serialization/portable/ClassDefinition.ts
  src/serialization/portable/ClassDefinitionContext.ts
  src/serialization/portable/DefaultPortableReader.ts
  src/serialization/portable/MorphingPortableReader.ts
  tslint.json
Labels: Type: Enhancement

#334 update address configuration
  CONFIG.md
Labels: Type: Documentation

#333 fix on LockProxyTest
  test/lock/LockProxyTest.js
Labels: Type: Test-Failure

#331 prevent client hanging due to incompatible server
  src/invocation/ClientConnectionManager.ts
  test/ConnectionManagerTest.js
Labels: Type: Defect

#327 implement Client Statistics and NearCacheManager
  src/BuildMetadata.ts
  src/HazelcastClient.ts
  src/Util.ts
  src/codec/ClientStatisticsCodec.ts
  src/config/Config.ts
  src/invocation/ClientConnection.ts
  src/invocation/ClusterService.ts
  src/nearcache/NearCache.ts
  src/nearcache/NearCacheManager.ts
  src/proxy/NearCachedMapProxy.ts
  src/statistics/Statistics.ts
  test/BuildMetadataTest.js
  test/RepetitionTaskTest.js
  test/map/NearCachedMapTest.js
  test/statistics/StatisticsTest.js
Labels: Type: Enhancement

#339 fix Lost connection test
  test/LostConnectionTest.js
Labels: Type: Test-Failure

#337 fix Listeners on reconnect tests
  test/ListenersOnReconnectTest.js
Labels: Type: Test-Failure
