Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2018-11, with the labels that each got.

#393 export EvictionPolicy
  code_samples/near_cache.js
  src/index.ts
Labels: Type: Enhancement

#395 Copyedit of the current Node.js Documentation
  README.md
Labels: Type: Documentation

#399 refactor getter functions in documentation
  README.md
Labels: Type: Documentation, Type: Enhancement

#396 refactor item listeners
  src/core/ItemListener.ts
  src/index.ts
  src/proxy/ListProxy.ts
  src/proxy/QueueProxy.ts
  src/proxy/SetProxy.ts
  test/list/ListProxyTest.js
  test/queue/QueueProxyTest.js
  test/set/SetProxyTest.js
Labels: Type: Enhancement

#398 add serialization priority to serialization chapter
  README.md
Labels: Type: Documentation

#401 fix wrong word
  README.md
Labels: Type: Documentation

#394 add Enabling Client Statistics doc
  README.md
Labels: Type: Documentation

#402 refactor interface names as Java
  src/HazelcastClient.ts
  src/proxy/ReplicatedMap.ts
  src/proxy/ReplicatedMapProxy.ts
  src/proxy/Ringbuffer.ts
  src/proxy/ringbuffer/RingbufferProxy.ts
  src/proxy/topic/ReliableTopicListenerRunner.ts
  src/proxy/topic/ReliableTopicProxy.ts
Labels: Type: Enhancement

#407 Fix enumeration of 1.2.2 - 1.2.4
  README.md
Labels: Type: Documentation

#406 Add logging configuration documentation
  README.md
Labels: Type: Documentation

#408 Mention hazelcast.client.invocation.retry.pause.millis property
  README.md
Labels: Type: Documentation

#411 refactor 1.2.1. Setting Up a Hazelcast IMDG Cluster starting options
  README.md
Labels: Type: Enhancement

#414 Migrate Promise.defer to new Promise
  src/ListenerService.ts
  src/Util.ts
  src/config/JsonConfigLocator.ts
  src/discovery/HazelcastCloudDiscovery.ts
  src/invocation/ClientConnection.ts
  src/invocation/ClientConnectionManager.ts
  src/invocation/ClusterService.ts
  src/invocation/InvocationService.ts
  src/nearcache/NearCache.ts
  src/proxy/ProxyManager.ts
  src/proxy/flakeid/AutoBatcher.ts
  test/HazelcastClientTest.js
  test/MembershipListenerTest.js
  test/RC.js
  test/flakeid/FlakeIdGeneratorProxyTest.js
  test/map/NearCachedMapStressTest.js
  test/nearcache/LostInvalidationsTest.js
  test/nearcache/MigratedDataTest.js
  test/serialization/config/CustomSerializerTest.js
  test/statistics/StatisticsTest.js
Labels: Type: Enhancement

#416 Update benchmark
  benchmark/SimpleMapBenchmark.js
Labels: Type: Enhancement

#405 add Near Cache documentation
  README.md
Labels: Type: Documentation

#397 add listeners documentation for data structures
  README.md
Labels: Type: Documentation

#413 make more clear the usage of client statistics
  README.md
Labels: Type: Documentation

#420 Fix wrong word
  README.md
Labels: Type: Documentation

#421 Refactor TopicMessageLister naming as Java
  README.md
  src/proxy/topic/ITopic.ts
  src/proxy/topic/Message.ts
  src/proxy/topic/MessageListener.ts
  src/proxy/topic/ReliableTopicListenerRunner.ts
  src/proxy/topic/ReliableTopicMessage.ts
  src/proxy/topic/ReliableTopicProxy.ts
  src/serialization/SerializationService.ts
  test/topic/TopicTest.js
Labels: Type: Enhancement

#419 remove unnecessary precompile
  create-build-info.js
  package.json
  src/BuildInfo.ts
  src/BuildInfoLoader.ts
  src/invocation/ClientConnection.ts
  src/invocation/ConnectionAuthenticator.ts
  src/proxy/BaseProxy.ts
  src/proxy/NearCachedMapProxy.ts
  src/statistics/Statistics.ts
  test/BuildInfoTest.js
  test/BuildMetadataTest.js
  test/Util.js
  test/statistics/StatisticsTest.js
Labels: Type: Cleanup, Type: Enhancement

#426 Final retouches to the current readme.
  README.md
Labels: Type: Documentation

#424 refactor membership listener
  code_samples/membership_listener.js
  src/core/MembershipEvent.ts
  src/core/MembershipListener.ts
  src/invocation/ClusterService.ts
  test/ClusterServiceTest.js
  test/HeartbeatTest.js
  test/LostConnectionTest.js
  test/MembershipListenerTest.js
Labels: Type: Enhancement

#425 Fix broken links in documentation
  README.md
Labels: Type: Defect
