Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2019-03, with the labels that each got.

#466 add jaas code samples
  README.md
  code_samples/jaas_sample/README.md
  code_samples/jaas_sample/admin_client.js
  code_samples/jaas_sample/hazelcast-member/README.md
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/Bootstrap.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/ClientLoginModule.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/DummyAuthenticator.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UserGroupCredentials.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UsernamePasswordCredentials.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UsernamePasswordCredentialsFactory.java
  code_samples/jaas_sample/hazelcast-member/src/main/resources/hazelcast.xml
  code_samples/jaas_sample/reader_client.js
  code_samples/jaas_sample/user_pass_cred.js
  code_samples/jaas_sample/user_pass_cred_factory.js
Labels: Type: Documentation

#467 Improve simple map benchmark
  benchmark/MapPutRunner.js
  benchmark/MapRandomOpRunner.js
  benchmark/README.md
  benchmark/SimpleBenchmark.js
  benchmark/SimpleMapBenchmark.js
Labels: Type: Enhancement

#468 implement Json serializer
  README.md
  code_samples/hazelcast_json_value.js
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
  src/Util.ts
  src/config/Config.ts
  src/config/ConfigBuilder.ts
  src/config/JsonStringDeserializationPolicy.ts
  src/config/SerializationConfig.ts
  src/core/HazelcastJsonValue.ts
  src/index.ts
  src/serialization/DefaultSerializer.ts
  src/serialization/SerializationService.ts
  test/MembershipListenerTest.js
  test/declarative_config/ConfigBuilderTest.js
  test/declarative_config/configurations/full.json
  test/hazelcast_json_value/HJVHazelcastJsonValueSerializerTest.js
  test/hazelcast_json_value/HJVJsonSerializerTest.js
  test/hazelcast_json_value/HazelcastJsonValueTest.js
  test/serialization/JsonSerializersTest.js
Labels: Type: Documentation, Type: Enhancement

#469 mention about dev dependency vulnerabilities in the readme
  README.md
Labels: Type: Documentation
