Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2019-04, with the labels that each got.

#465 update readme and code samples
  README.md
  code_samples/org-website/AtomicLongSample.js
  code_samples/org-website/LockSample.js
  code_samples/org-website/ReliableTopicSample.js
  hazelcast-client-full.json
Labels: Type: Cleanup

#471 log lifecycle events with the info level
  README.md
  src/HazelcastClient.ts
  src/LifecycleService.ts
Labels: Type: Defect

#473 Enhancement/performance optimizations
  README.md
  benchmark/MapGetRunner.js
  benchmark/README.md
  config-schema.json
  hazelcast-client-full.json
  package-lock.json
  package.json
  src/BitsUtil.ts
  src/ClientMessage.ts
  src/config/Config.ts
  src/config/ConfigBuilder.ts
  src/config/SerializationConfig.ts
  src/config/StringSerializationPolicy.ts
  src/index.ts
  src/invocation/ClientConnection.ts
  src/invocation/ClientConnectionManager.ts
  src/invocation/InvocationService.ts
  src/serialization/Data.ts
  src/serialization/HeapData.ts
  src/serialization/ObjectData.ts
  src/serialization/SerializationService.ts
  test/declarative_config/ConfigBuilderTest.js
  test/declarative_config/configurations/full.json
  test/serialization/APortable.js
  test/serialization/AnIdentifiedDataSerializable.js
  test/serialization/BinaryCompatibilityTest.js
  test/serialization/DefaultSerializersLiveTest.js
  test/serialization/DefaultSerializersTest.js
  test/serialization/ObjectDataTest.js
  test/serialization/PortableObjects.js
  test/serialization/PortableTest.js
  test/serialization/ReferenceObjects.js
Labels: Type: Enhancement
