Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2019-01, with the labels that each got.

#443 marks some tests with minimum required server versions
  test/HeartbeatTest.js
  test/LostConnectionTest.js
  test/ssl/ClientSSLTest.js
  test/statistics/StatisticsTest.js
  test/topic/TopicTest.js
Labels: Type: Cleanup, Type: Enhancement

#450 Fixes client not sending pings when server continuosly pushes messages
  src/HeartbeatService.ts
  src/invocation/ClientConnection.ts
  test/heartbeat/HeartbeatFromClientTest.js
  test/heartbeat/HeartbeatFromServerTest.js
  test/heartbeat/short-heartbeat.xml
Labels: Type: Defect

#451 Adds missing os.systemLoadAverage
  src/Util.ts
  src/statistics/Statistics.ts
  test/statistics/StatisticsTest.js
Labels: Type: Defect

#456 update hazelcast version to use the renewed certificates
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Type: Test-Failure

#458 remove member tool section from the documentation
  README.md
Labels: Type: Documentation

#459 add missing line to the cluster section
  README.md
Labels: Type: Documentation
