Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2020-08, with the labels that each got.

#567 Fix ReliableTopic implementation
  src/invocation/InvocationService.ts
  src/proxy/Ringbuffer.ts
  src/proxy/ringbuffer/LazyReadResultSet.ts
  src/proxy/ringbuffer/ReadResultSet.ts
  src/proxy/ringbuffer/RingbufferProxy.ts
  src/proxy/topic/ReliableTopicListenerRunner.ts
  test/ringbuffer/LazyReadResultSetTest.js
  test/ringbuffer/RingbufferProxyTest.js
  test/ringbuffer/RingbufferTest.js
  test/topic/ReliableTopicTest.js
Labels: Priority: High, Source: Internal, Type: Defect

#571 Remove handled fragmented messages from the map
  src/network/ClientConnection.ts
  test/connection/FragmentedClientMessageHandlerTest.js
Labels: Source: Internal, Type: Defect

#572 Add Buffer type support
  DOCUMENTATION.md
  src/serialization/Data.ts
  src/serialization/ObjectData.ts
  src/serialization/Portable.ts
  src/serialization/SerializationService.ts
  src/serialization/portable/ClassDefinitionWriter.ts
  src/serialization/portable/DefaultPortableReader.ts
  src/serialization/portable/DefaultPortableWriter.ts
  src/serialization/portable/MorphingPortableReader.ts
  src/util/Util.ts
  test/serialization/APortable.js
  test/serialization/AnIdentifiedDataSerializable.js
  test/serialization/BinaryCompatibilityTest.js
  test/serialization/DefaultSerializersLiveTest.js
  test/serialization/DefaultSerializersTest.js
  test/serialization/IdentifiedDataSerializableTest.js
  test/serialization/ObjectDataTest.js
  test/serialization/PortableObjects.js
  test/serialization/PortableSerializationTest.js
  test/serialization/ReferenceObjects.js
Labels: Source: Internal, Type: Enhancement

#573 Add boomerang backups support
  DOCUMENTATION.md
  src/HazelcastClient.ts
  src/config/Config.ts
  src/config/ConfigBuilder.ts
  src/core/HazelcastError.ts
  src/invocation/InvocationService.ts
  src/listener/ListenerMessageCodec.ts
  src/listener/ListenerService.ts
  src/protocol/ClientMessage.ts
  src/protocol/ErrorFactory.ts
  src/util/BitsUtil.ts
  test/config/ConfigBuilderTest.js
  test/config/SchemaValidationTest.js
  test/config/configurations/config-schema.json
  test/config/configurations/full.json
  test/integration/ClientBackupAcksTest.js
  test/integration/ClientLabelTest.js
  test/invocation/InvocationServiceTest.js
  test/invocation/InvocationTest.js
  test/nearcache/LostInvalidationsTest.js
  test/unit/protocol/ClientMessageTest.js
Labels: Source: Internal, Type: Enhancement

#574 Change minimal Node.js version to 10
  .eslintrc.js
  DOCUMENTATION.md
  package.json
  src/invocation/RegistrationKey.ts
  src/listener/ListenerService.ts
  src/network/ClientConnection.ts
  src/protocol/ClientMessage.ts
  src/proxy/MapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  src/proxy/ProxyManager.ts
  src/proxy/ReplicatedMapProxy.ts
  src/proxy/topic/ReliableTopicProxy.ts
  src/serialization/ObjectData.ts
  src/serialization/SerializationService.ts
  src/serialization/SerializationUtil.ts
  src/serialization/portable/MorphingPortableReader.ts
Labels: Source: Internal, Type: Cleanup

#576 Add serverStackTrace property in HazelcastError class
  src/core/HazelcastError.ts
  src/protocol/ErrorFactory.ts
  src/protocol/StackTraceElement.ts
  test/unit/protocol/ClientErrorFactoryTest.js
Labels: Priority: Low, Source: Internal, Type: Enhancement

#575 Add test to verify that member list is not broken after hot restart
  download-remote-controller.js
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
  src/invocation/ClusterService.ts
  src/network/ClientConnectionManager.ts
  test/AutoPipeliningDisabledTest.js
  test/ClientHotRestartEventTest.js
  test/RC.js
  test/Util.js
  test/remote_controller/Controller.js
  test/remote_controller/RemoteController.js
  test/remote_controller/remote-controller_types.js
Labels: Type: Cleanup
