Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2020-11, with the labels that each got.

#653 Increase timeout in LostProxyTest
  test/lock/LockProxyTest.js
Labels: Source: Internal, Type: Test-Failure

#654 Remove source maps from npm artifact
  tsconfig.json
Labels: Source: Internal, Type: Cleanup

#624 Fix #535: Change Long into number for correlationId
  src/codec/builtin/FixSizedTypesCodec.ts
  src/protocol/ClientMessage.ts
  test/unit/codec/builtin/FixSizedTypesCodecTest.js
  test/unit/protocol/ClientMessageTest.js
Labels: Source: Community, Type: Enhancement

#656 Fix code samples link in readme
  README.md
Labels: Source: Internal, Type: Defect, Type: Documentation

#657 Fix code samples link in readme
  README.md
Labels: Backport, Source: Internal, Type: Defect, Type: Documentation

#659 Fix missing release session calls in SessionAwareSemaphoreProxy
  src/proxy/cpsubsystem/SessionAwareSemaphoreProxy.ts
  test/unit/proxy/cpsubsystem/SessionAwareSemaphoreProxyTest.js
Labels: Source: Internal, Type: Defect

#660 [BACKPORT] Fix missing release session calls in SessionAwareSemaphoreProxy
  src/proxy/cpsubsystem/SessionAwareSemaphoreProxy.ts
  test/unit/proxy/cpsubsystem/SessionAwareSemaphoreProxyTest.js
Labels: Backport, Source: Internal, Type: Defect

#662 Reject/retry pending invocations on connection close
  src/ClientMessage.ts
  src/HazelcastClient.ts
  src/config/ClientNetworkConfig.ts
  src/config/Config.ts
  src/invocation/InvocationService.ts
  test/lock/LockProxyTest.js
  test/nearcache/LostInvalidationsTest.js
Labels: Priority: High, Source: Internal, Type: Defect

#665 Cover murmurhash3 implementation with unit tests
  src/invocation/Murmur.ts
  test/unit/invocation/MurmurTest.js
Labels: Source: Internal, Type: Cleanup

#667 Improve Docker instructions in benchmark readme
  benchmark/README.md
Labels: Source: Internal, Type: Documentation

#668 Update IMDG test version to 4.1
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Source: Internal, Type: Cleanup

#664 Fix test flakiness on Windows
  src/PartitionService.ts
  src/invocation/ClusterService.ts
  test/ClientClusterRestartEventTest.js
  test/ClusterServiceTest.js
  test/heartbeat/HeartbeatFromClientTest.js
  test/heartbeat/HeartbeatFromServerTest.js
  test/mocha.opts
  test/nearcache/NearCacheSimpleInvalidationTest.js
Labels: Source: Internal, Type: Test-Failure

#670 Fix incorrect splice usage in NearCachedMapProxy#getAllInternal
  src/proxy/MapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  test/map/NearCachedMapTest.js
Labels: Source: Internal, Type: Defect

#673 [FORWARD-PORT] Fix incorrect splice usage in NearCachedMapProxy#getAllInternal
  src/proxy/MapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  test/map/NearCachedMapTest.js
Labels: Forwardport, Source: Internal, Type: Defect

#672 [FORWARD-PORT] Fix incorrect splice usage in NearCachedMapProxy#getAllInternal
  src/proxy/MapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  test/map/NearCachedMapTest.js
Labels: Forwardport, Source: Internal, Type: Defect

#675 [FORWARD-PORT] Update Java snippets to 4.0 API
  DOCUMENTATION.md
  code_samples/jaas_sample/hazelcast-member/README.md
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/Bootstrap.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/ClientLoginModule.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/DummyAuthenticator.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UserGroupCredentials.java
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UsernamePasswordCredentials.java
  code_samples/jaas_sample/hazelcast-member/src/main/resources/hazelcast.xml
Labels: Source: Internal, Type: Documentation

#676 Update IMDG version to 3.12.10 in tests
  code_samples/soak_test/perf-bench.sh
  code_samples/soak_test/start-server.sh
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Source: Internal, Type: Cleanup

#677 Fix backup acks listener registration on client start
  src/HazelcastClient.ts
  src/invocation/InvocationService.ts
  src/listener/ListenerService.ts
  test/integration/ClientBackupAcksTest.js
  test/invocation/InvocationServiceTest.js
Labels: Priority: High, Source: Internal, Type: Defect

#683 Fix floating promises
  .eslintrc.js
  src/nearcache/NearCache.ts
  src/network/ClientConnectionManager.ts
  src/proxy/NearCachedMapProxy.ts
  src/proxy/topic/ReliableTopicProxy.ts
  tsconfig.eslint.json
Labels: Source: Internal, Type: Cleanup

#682 [BACKPORT] Fix backup acks listener registration on client start
  src/HazelcastClient.ts
  src/invocation/InvocationService.ts
  src/listener/ListenerService.ts
  test/integration/ClientBackupAcksTest.js
  test/invocation/InvocationServiceTest.js
Labels: Priority: High, Source: Internal, Type: Defect

#686 [BACKPORT] Fix floating promises
  .eslintrc.js
  src/nearcache/NearCache.ts
  src/network/ClientConnectionManager.ts
  src/proxy/NearCachedMapProxy.ts
  src/proxy/topic/ReliableTopicProxy.ts
  tsconfig.eslint.json
Labels: Backport, Source: Internal, Type: Cleanup

#688 Improve code style in tests
  test/ClusterServiceTest.js
  test/ConnectionManagerTest.js
  test/HazelcastClientTest.js
  test/ListenerServiceTest.js
  test/cpsubsystem/FencedLockTest.js
  test/integration/ClientBackupAcksTest.js
  test/integration/ClientLabelTest.js
  test/integration/DistributedObjectsTest.js
  test/integration/InitialMembershipListenerTest.js
  test/nearcache/LostInvalidationsTest.js
  test/nearcache/MigratedDataTest.js
  test/nearcache/impl/RepairingTaskTest.js
  test/ringbuffer/RingbufferProxyTest.js
  test/ssl/ClientSSLAuthenticationTest.js
  test/statistics/StatisticsTest.js
  test/topic/ReliableTopicTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
Labels: Source: Internal, Type: Cleanup

#689 Fix client resource leak on failed start
  src/HazelcastClient.ts
  src/network/ClientConnectionManager.ts
  src/proxy/cpsubsystem/CPSessionManager.ts
  test/ClientProxyTest.js
  test/ClientShutdownTest.js
  test/HazelcastClientTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
Labels: Source: Internal, Type: Defect

#692 [BACKPORT] Fix client resource leak on failed start
  src/HazelcastClient.ts
  src/network/ClientConnectionManager.ts
  src/proxy/cpsubsystem/CPSessionManager.ts
  test/ClientProxyTest.js
  test/ClientShutdownTest.js
  test/HazelcastClientTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
Labels: Source: Internal, Type: Defect

#693 Workaround ClientBackupAcksTest flakiness
  test/integration/ClientBackupAcksTest.js
Labels: Priority: High, Source: Internal, Type: Test-Failure

#694 [BACKPORT] Workaround ClientBackupAcksTest flakiness
  test/integration/ClientBackupAcksTest.js
Labels: Backport, Priority: High, Source: Internal, Type: Test-Failure

#695 Update IMDG version to 4.0.3
  README.md
  benchmark/README.md
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
  test/soak_test/perf-bench.sh
  test/soak_test/start-server.sh
Labels: Source: Internal, Type: Cleanup
