Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2020-06, with the labels that each got.

#540 Fix unhandled promise rejection in getDistributedObjects()
  src/HazelcastClient.ts
Labels: Type: Critical, Type: Defect

#532 Remove string serialization policy
  DOCUMENTATION.md
  config-schema.json
  hazelcast-client-default.json
  hazelcast-client-full.json
  src/config/Config.ts
  src/config/ConfigBuilder.ts
  src/config/SerializationConfig.ts
  src/config/StringSerializationPolicy.ts
  src/index.ts
  src/serialization/ObjectData.ts
  src/serialization/SerializationService.ts
  test/declarative_config/ConfigBuilderTest.js
  test/declarative_config/configurations/full.json
  test/serialization/DefaultSerializersTest.js
  test/serialization/ObjectDataTest.js
Labels: Source: Internal, Type: Cleanup

#533 Remove safe buffer dependency
  package.json
  src/BitsUtil.ts
  src/ClientMessage.ts
  src/codec/ClientAuthenticationCustomCodec.ts
  src/codec/ClientStatisticsCodec.ts
  src/codec/builtin/ByteArrayCodec.ts
  src/codec/builtin/EntryListIntegerIntegerCodec.ts
  src/codec/builtin/EntryListIntegerLongCodec.ts
  src/codec/builtin/EntryListIntegerUUIDCodec.ts
  src/codec/builtin/EntryListLongByteArrayCodec.ts
  src/codec/builtin/EntryListUUIDLongCodec.ts
  src/codec/builtin/EntryListUUIDUUIDCodec.ts
  src/codec/builtin/FixSizedTypesCodec.ts
  src/codec/builtin/ListIntegerCodec.ts
  src/codec/builtin/ListLongCodec.ts
  src/codec/builtin/ListUUIDCodec.ts
  src/codec/builtin/StringCodec.ts
  src/network/ClientConnection.ts
  src/network/ClientConnectionManager.ts
  src/serialization/Data.ts
  src/serialization/HeapData.ts
  src/serialization/ObjectData.ts
  src/serialization/SerializationService.ts
  src/statistics/Statistics.ts
  test/connection/ClientMessageReaderTest.js
  test/connection/DirectWriterTest.js
  test/connection/FragmentedClientMessageHandlerTest.js
  test/connection/PipelinedWriterTest.js
  test/rest_value/RestValueTest.js
  test/serialization/APortable.js
  test/serialization/AnIdentifiedDataSerializable.js
  test/serialization/BinaryCompatibilityTest.js
  test/serialization/ObjectDataTest.js
  test/serialization/ReferenceObjects.js
  test/unit/protocol/ClientMessageFramingTest.js
  test/unit/protocol/ClientMessageTest.js
Labels: Source: Internal, Type: Cleanup

#547 Improve ListenerServiceTest
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
  test/ListenerServiceTest.js
Labels: Source: Internal, Type: Cleanup

#546 Fix ListenerServiceTest
  scripts/dev-test-rc.sh
  scripts/download-rc.bat
  scripts/download-rc.sh
  test/ListenerServiceTest.js
Labels: Backport, Source: Internal, Type: Defect

#550 Update Hazelcast Cloud documentation and code sample
  DOCUMENTATION.md
  code_samples/hazelcast_cloud_discovery.js
Labels: Type: Defect, Type: Documentation
