Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2020-10, with the labels that each got.

#620 Fix timeout error handling in CountDownLatchProxy#countDown
  src/proxy/cpsubsystem/CountDownLatchProxy.ts
Labels: Priority: Medium, Source: Internal, Type: Defect

#621 [FORWARD-PORT] Fix timeout error handling in CountDownLatchProxy#countDown
  src/proxy/cpsubsystem/CountDownLatchProxy.ts
Labels: Forwardport, Priority: Medium, Source: Internal, Type: Defect

#617 [BACKPORT] Fix StatisticsTest on windows
  test/statistics/StatisticsTest.js
Labels: Backport, Source: Internal, Type: Test-Failure

#615 [BACKPORT] Mark CannotReplicateError as retryable
  src/core/HazelcastError.ts
Labels: Backport, Source: Internal, Type: Defect

#614 Mark CannotReplicateError as retryable
  src/core/HazelcastError.ts
Labels: Source: Internal, Type: Defect

#618 Fix timeout exception on lock operations when member dies
  src/invocation/InvocationService.ts
  src/proxy/BaseProxy.ts
  src/proxy/LockProxy.ts
  src/proxy/MapProxy.ts
  src/proxy/PartitionSpecificProxy.ts
  test/lock/LockProxyTest.js
Labels: Priority: High, Type: Defect

#622 [FORWARD-PORT] Fix timeout exception on map lock operations when member dies
  src/PartitionService.ts
  src/invocation/InvocationService.ts
  src/proxy/BaseProxy.ts
  src/proxy/MapProxy.ts
  test/map/MapLockTest.js
  test/map/MapProxyTest.js
Labels: Forwardport, Priority: High, Type: Defect

#623 [FORWARD-PORT] Fix timeout exception on map lock operations when member dies
  src/PartitionService.ts
  src/invocation/InvocationService.ts
  src/proxy/BaseProxy.ts
  src/proxy/MapProxy.ts
  test/map/MapLockTest.js
  test/map/MapProxyTest.js
Labels: Forwardport, Priority: High, Type: Defect

#628 Migrating some tests to Async/Await
  test/LifecycleServiceTest.js
  test/MembershipListenerTest.js
  test/RepetitionTaskTest.js
  test/map/MapEntryProcessorTest.js
  test/map/MapPredicateTest.js
  test/map/MapStoreTest.js
  test/rest_value/RestValueTest.js
  test/statistics/StatisticsTest.js
Labels: Source: Community

#638 Migrated List, Map, MultiMap, ReplicatedMap, Queue and Set tests to async/await
  test/list/ListProxyTest.js
  test/map/MapAggregatorsDoubleTest.js
  test/map/MapAggregatorsIntTest.js
  test/map/MapAggregatorsLongTest.js
  test/map/MapPartitionAwareTest.js
  test/map/MapProxyTest.js
  test/map/NearCachedMapStressTest.js
  test/map/NearCachedMapTest.js
  test/multimap/MultiMapProxyListenersTest.js
  test/multimap/MultiMapProxyLockTest.js
  test/multimap/MultiMapProxyTest.js
  test/queue/QueueProxyTest.js
  test/replicatedmap/ReplicatedMapProxyTest.js
  test/set/SetProxyTest.js
Labels: Source: Community

#627 [BACKPORT] Improve listener deregistration logic
  src/listener/ListenerService.ts
  test/ListenerServiceTest.js
Labels: Backport, Source: Internal, Type: Cleanup, Type: Enhancement

#631 Increase backup ack timeout in ClientBackupAcksTest
  test/integration/ClientBackupAcksTest.js
Labels: Source: Internal, Type: Test-Failure

#632 [FORWARD-PORT] Increase backup ack timeout in ClientBackupAcksTest
  test/integration/ClientBackupAcksTest.js
Labels: Forwardport, Source: Internal, Type: Test-Failure

#633 Fix invalid Promise<void> conversions
  .eslintrc.js
  src/proxy/ListProxy.ts
  src/proxy/MapProxy.ts
  src/proxy/MultiMapProxy.ts
  src/proxy/ProxyManager.ts
  src/proxy/QueueProxy.ts
  src/proxy/ReplicatedMapProxy.ts
  src/proxy/SetProxy.ts
  src/proxy/cpsubsystem/AtomicLongProxy.ts
  src/proxy/cpsubsystem/AtomicRefProxy.ts
  src/proxy/cpsubsystem/BaseCPProxy.ts
  src/proxy/cpsubsystem/CPSessionManager.ts
  src/proxy/cpsubsystem/CountDownLatchProxy.ts
  src/proxy/cpsubsystem/SessionAwareSemaphoreProxy.ts
  src/proxy/cpsubsystem/SessionlessSemaphoreProxy.ts
Labels: Source: Internal, Type: Defect

#634 [FORWARD-PORT] Fix invalid Promise<void> conversions
  .eslintrc.js
  src/proxy/ListProxy.ts
  src/proxy/MapProxy.ts
  src/proxy/MultiMapProxy.ts
  src/proxy/ProxyManager.ts
  src/proxy/QueueProxy.ts
  src/proxy/ReplicatedMapProxy.ts
  src/proxy/SetProxy.ts
  src/proxy/cpsubsystem/AtomicLongProxy.ts
  src/proxy/cpsubsystem/AtomicRefProxy.ts
  src/proxy/cpsubsystem/BaseCPProxy.ts
  src/proxy/cpsubsystem/CPSessionManager.ts
  src/proxy/cpsubsystem/CountDownLatchProxy.ts
  src/proxy/cpsubsystem/SessionAwareSemaphoreProxy.ts
  src/proxy/cpsubsystem/SessionlessSemaphoreProxy.ts
Labels: Forwardport, Source: Internal, Type: Defect

#644 Fix flaky tests
  src/nearcache/MetadataFetcher.ts
  src/nearcache/RepairingTask.ts
  test/config/SchemaValidationTest.js
Labels: Source: Internal, Type: Test-Failure

#645 [BACKPORT] Fix flaky tests
  src/nearcache/MetadataFetcher.ts
  src/nearcache/RepairingTask.ts
  test/config/SchemaValidationTest.js
Labels: Backport, Source: Internal, Type: Test-Failure

#641 Release session on unexpected FencedLock error
  src/proxy/cpsubsystem/FencedLockProxy.ts
  test/unit/proxy/cpsubsystem/FencedLockProxyTest.js
Labels: Source: Internal, Type: Defect

#640 Add getAndDecrement operation for AtomicLong
  src/proxy/IAtomicLong.ts
  src/proxy/cpsubsystem/AtomicLongProxy.ts
  test/cpsubsystem/AtomicLongTest.js
Labels: Source: Internal, Type: Enhancement

#642 [BACKPORT] Release session on unexpected FencedLock error
  src/proxy/cpsubsystem/FencedLockProxy.ts
  test/unit/proxy/cpsubsystem/FencedLockProxyTest.js
Labels: Backport, Source: Internal, Type: Defect

#626 Improve listener deregistration
  src/listener/ListenerService.ts
  test/ListenerServiceTest.js
Labels: Source: Internal, Type: Cleanup, Type: Enhancement

#648 Fix null request handling in listener deregistration
  src/listener/ListenerService.ts
Labels: Priority: High, Source: Internal, Type: Defect

#649 [BACKPORT] Fix null request handling in listener deregistration
  src/listener/ListenerService.ts
Labels: Backport, Priority: High, Source: Internal, Type: Defect
