Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2021-05, with the labels that each got.

#879 Update server version 4.1.x
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Estimation: S, Source: Internal, Type: Test-Failure

#882 Add markdown link checker
  .github/workflows/markdown_link_checker.yml
  DOCUMENTATION.md
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Documentation, Type: Enhancement

#888 Fix typo in docs about invocation timeout property
  DOCUMENTATION.md
Labels: Estimation: S, Source: Internal, Type: Documentation

#893 [API-376] Add non stop near cache test
  test/integration/backward_compatible/nearcache/NonStopNearCache.js
Labels: Estimation: S, Source: Internal, Type: Defect

#895 [API-375] Add connection retry validation
  DOCUMENTATION.md
  src/config/ConfigBuilder.ts
  test/unit/config/ConfigBuilderTest.js
Labels: Estimation: S, Source: Internal, Type: Enhancement

#854 Switch to typescript coverage
  .nycrc.json
  package.json
  tsconfig.json
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Enhancement

#871 [API-378] Make defaultNumberType usage clear
  DOCUMENTATION.md
  src/config/ConfigBuilder.ts
  src/config/SerializationConfig.ts
  test/unit/config/configurations/config-schema.json
  test/unit/serialization/DefaultSerializersTest.js
  typedoc.json
Labels: Estimation: S, Source: Internal, Type: Documentation, Type: Enhancement

#896 [API-374] Fire membership events when hot restart persistence is enabled
  src/HazelcastClient.ts
  src/invocation/ClusterService.ts
  test/integration/backward_compatible/ClientHotRestartEventTest.js
Labels: Estimation: S, Source: Internal, Type: Defect

#904 [API-424] Do not allow concurrent requests on SessionManager for the same group id
  src/proxy/cpsubsystem/CPSessionManager.ts
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
Labels: Source: Internal, Type: Defect

#859 [API-296]Add datetime related wrapper classes
  src/core/DatetimeClasses.ts
  src/core/index.ts
  src/util/DatetimeUtil.ts
  test/unit/core/DatetimeWrapperClasses.js
  test/unit/util/DatetimeUtil.js
Labels: Estimation: M, Source: Internal, Type: Enhancement

#890 [API-377] Add reliable topic cluster restart tests
  test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js
Labels: Estimation: S, Source: Internal, Type: Enhancement

#919 Add `curly` and `keyword-spacing` rules to eslint
  .eslintignore
  .eslintrc
  code_samples/paging_predicate.js
  scripts/test-runner.js
  src/.eslintrc.js
  src/codec/builtin/FixSizedTypesCodec.ts
  src/config/ConfigBuilder.ts
  src/proxy/ProxyManager.ts
  src/serialization/portable/DefaultPortableWriter.ts
  src/util/DatetimeUtil.ts
  test/integration/RC.js
  test/integration/backward_compatible/topic/ReliableTopicOnClusterRestart.js
  test/unit/serialization/APortable.js
  test/unit/serialization/AnIdentifiedDataSerializable.js
  test/unit/serialization/AnInnerPortable.js
Labels: Source: Internal, Type: Enhancement
