Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2021-02, with the labels that each got.

#799 Add missing registration for default list serializers
  src/serialization/SerializationService.ts
  test/integration/serialization/DefaultSerializersLiveTest.js
Labels: Source: Internal, Type: Defect

#800 [BACKPORT] Add missing registration for default list serializers
  src/serialization/SerializationService.ts
  test/integration/serialization/DefaultSerializersLiveTest.js
Labels: Backport, Source: Internal, Type: Defect

#795 Usage of node.js script to download RC instead of .sh and .bat scripts #752
  .gitignore
  .npmignore
  download-remote-controller.js
  package.json
  scripts/dev-test-rc.sh
  scripts/download-and-run-rc.js
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Source: Community, Type: Enhancement

#796 [BACKPORT ] v3.12 Clear resources on start fail #690
  scripts/download-rc.sh
  src/HazelcastClient.ts
  test/ClientProxyTest.js
  test/ClientShutdownTest.js
  test/HazelcastClientTest.js
Labels: Source: Community, Type: Defect

#804 Kill RC process after integration test execution
  README.md
  package.json
  scripts/download-and-run-rc.js
  scripts/download-rc.js
  scripts/test-runner.js
Labels: Source: Internal, Type: Enhancement
