Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2021-04, with the labels that each got.

#817 [API-238]Typescript strict flags
  src/proxy/MapListener.ts
  src/proxy/MapProxy.ts
  src/proxy/NearCachedMapProxy.ts
  src/proxy/ReplicatedMapProxy.ts
  tsconfig.json
Labels: Estimation: M, Priority: Medium, Source: Internal, Type: Enhancement

#862 Fix client version handling in the statistics tests
  test/integration/backward_compatible/statistics/StatisticsTest.js
Labels: Source: Internal, Type: Test-Failure

#863 Use assertTrueEventually instead of setTimeout for getDistributedObjects test
  .eslintrc
  package.json
  test/.eslintrc
  test/TestUtil.js
  test/integration/ConnectionManagerTest.js
  test/integration/RC.js
  test/integration/backward_compatible/ClientReconnectTest.js
  test/integration/backward_compatible/ClusterServiceTest.js
  test/integration/backward_compatible/HazelcastClientTest.js
  test/integration/backward_compatible/LifecycleServiceTest.js
  test/integration/backward_compatible/ListenerServiceTest.js
  test/integration/backward_compatible/ListenersOnReconnectTest.js
  test/integration/backward_compatible/LostConnectionTest.js
  test/integration/backward_compatible/flakeid/FlakeIdGeneratorProxyTest.js
  test/integration/backward_compatible/list/ListProxyTest.js
  test/integration/backward_compatible/map/MapEntryProcessorTest.js
  test/integration/backward_compatible/map/MapLockTest.js
  test/integration/backward_compatible/map/MapPartitionAwareTest.js
  test/integration/backward_compatible/map/MapProxyTest.js
  test/integration/backward_compatible/map/MapStoreTest.js
  test/integration/backward_compatible/map/NearCachedMapStressTest.js
  test/integration/backward_compatible/map/NearCachedMapTest.js
  test/integration/backward_compatible/multimap/MultiMapProxyListenersTest.js
  test/integration/backward_compatible/multimap/MultiMapProxyLockTest.js
  test/integration/backward_compatible/multimap/MultiMapProxyTest.js
  test/integration/backward_compatible/nearcache/InvalidationMetadataDistortionTest.js
  test/integration/backward_compatible/nearcache/NearCacheSimpleInvalidationTest.js
  test/integration/backward_compatible/queue/QueueProxyTest.js
  test/integration/backward_compatible/replicatedmap/ReplicatedMapProxyTest.js
  test/integration/backward_compatible/set/SetProxyTest.js
  test/integration/backward_compatible/ssl/ClientSSLAuthenticationTest.js
  test/integration/backward_compatible/topic/ReliableTopicTest.js
  test/integration/heartbeat/HeartbeatFromClientTest.js
  test/integration/remote_controller/Controller.js
  test/soak_test/map_soak_test.js
  test/unit/connection/DirectWriterTest.js
  test/unit/discovery/HazelcastCloudProviderTest.js
  test/unit/hazelcast_json_value/HazelcastJsonValueTest.js
  test/unit/nearcache/NearCacheTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
  test/unit/serialization/BinaryCompatibilityTest.js
  test/unit/serialization/DefaultSerializersTest.js
  test/unit/serialization/ObjectDataTest.js
Labels: Estimation: S, Source: Internal, Type: Enhancement

#837 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other-issues.md
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Documentation

#870 Change server version and disable transitive download
  scripts/download-rc.js
Labels: Estimation: S, Priority: High, Type: Test-Failure

#874 Update server version
  scripts/download-rc.bat
  scripts/download-rc.sh
Labels: Estimation: S, Source: Internal, Type: Defect

#873 Add junit mocha reporter
  .mocharc.json
  package.json
  scripts/test-runner.js
  test/integration/backward_compatible/LoggingTest.js
Labels: Estimation: S, Source: Internal, Type: Enhancement

#865 Delete unused chai.should() statements
  test/integration/ConnectionManagerTest.js
  test/integration/ConnectionManagerTranslateTest.js
  test/integration/backward_compatible/ClientBackupAcksTest.js
  test/integration/backward_compatible/ClientFailoverTest.js
  test/integration/backward_compatible/ClientRedoEnabledTest.js
  test/integration/backward_compatible/ClusterServiceTest.js
  test/integration/backward_compatible/cpsubsystem/AtomicLongTest.js
  test/integration/backward_compatible/cpsubsystem/AtomicReferenceTest.js
  test/integration/backward_compatible/cpsubsystem/CountDownLatchTest.js
  test/integration/backward_compatible/cpsubsystem/FencedLockTest.js
  test/integration/backward_compatible/cpsubsystem/SemaphoreCommonTest.js
  test/integration/backward_compatible/cpsubsystem/SessionAwareSemaphoreTest.js
  test/integration/backward_compatible/cpsubsystem/SessionlessSemaphoreTest.js
  test/integration/backward_compatible/map/MapPredicateTest.js
  test/unit/ClusterFailoverServiceBuilderTest.js
  test/unit/ClusterFailoverServiceTest.js
  test/unit/connection/DefaultAddressProviderTest.js
  test/unit/discovery/HazelcastCloudDiscoveryTest.js
  test/unit/invocation/InvocationServiceTest.js
  test/unit/network/TranslateAddressProviderTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
  test/unit/proxy/cpsubsystem/FencedLockProxyTest.js
  test/unit/proxy/cpsubsystem/SessionAwareSemaphoreProxyTest.js
  test/unit/util/UtilTest.js
Labels: Priority: Low, Source: Internal, Type: Cleanup
