Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2021-03, with the labels that each got.

#810 Fix pattern with space in test runner
  scripts/test-runner.js
Labels: Type: Cleanup

#808 Eslint rule changes & linting
  .eslintignore
  .eslintrc
  code_samples/.eslintrc
  code_samples/global_serializer.js
  code_samples/hazelcast_json_value.js
  code_samples/jaas_sample/reader_client.js
  code_samples/membership_listener.js
  code_samples/org-website/ListSample.js
  code_samples/org-website/QueueSample.js
  code_samples/paging_predicate.js
  package.json
  scripts/download-rc.js
  scripts/test-runner.js
  src/.eslintrc.js
  test/.eslintrc
  test/integration/ClientFailoverTest.js
  test/integration/ClientReconnectTest.js
  test/integration/ConnectionManagerTest.js
  test/integration/InitialMembershipListenerTest.js
  test/integration/MembershipListenerTest.js
  test/integration/cpsubsystem/AtomicLongTest.js
  test/integration/cpsubsystem/AtomicReferenceTest.js
  test/integration/cpsubsystem/CountDownLatchTest.js
  test/integration/cpsubsystem/FencedLockTest.js
  test/integration/cpsubsystem/SemaphoreCommonTest.js
  test/integration/cpsubsystem/SessionAwareSemaphoreTest.js
  test/integration/cpsubsystem/SessionlessSemaphoreTest.js
  test/integration/map/MapEntryProcessorTest.js
  test/integration/map/MapPredicateTest.js
  test/integration/map/MapProxyTest.js
  test/integration/map/MapStoreTest.js
  test/integration/multimap/MultiMapProxyListenersTest.js
  test/integration/multimap/MultiMapProxyLockTest.js
  test/integration/multimap/MultiMapProxyTest.js
  test/integration/nearcache/MigratedDataTest.js
  test/integration/queue/QueueProxyTest.js
  test/integration/rest_value/RestValueTest.js
  test/integration/serialization/Foo.js
  test/integration/serialization/Musician.js
  test/integration/set/SetProxyTest.js
  test/integration/statistics/StatisticsTest.js
  test/soak_test/map_soak_test.js
  test/unit/BuildInfoTest.js
  test/unit/RepetitionTaskTest.js
  test/unit/config/ConfigBuilderTest.js
  test/unit/connection/DirectWriterTest.js
  test/unit/connection/FragmentedClientMessageHandlerTest.js
  test/unit/core/UuidTest.js
  test/unit/discovery/HazelcastCloudProviderTest.js
  test/unit/proxy/cpsubsystem/CPSessionManagerTest.js
  test/unit/proxy/cpsubsystem/SemaphoreProxyCommonTest.js
  test/unit/serialization/AnInnerPortable.js
  test/unit/serialization/BinaryCompatibilityTest.js
  test/unit/serialization/DefaultSerializersTest.js
  test/unit/serialization/PortableObjects.js
  test/unit/serialization/PortableSerializationTest.js
  test/unit/serialization/portable/ClassDefinitionTest.js
  test/unit/serialization/portable/NestedPortableVersionTest.js
  test/unit/ssl/BasicSSLOptionsFactoryTest.js
Labels: Type: Cleanup

#818 Refactor jsdocs
  src/CPSubsystem.ts
  src/HazelcastClient.ts
  src/LifecycleService.ts
  src/config/BitmapIndexOptions.ts
  src/config/ClientNetworkConfig.ts
  src/config/Config.ts
  src/config/ConnectionStrategyConfig.ts
  src/config/NearCacheConfig.ts
  src/connection/AddressProvider.ts
  src/core/Address.ts
  src/core/ClientInfo.ts
  src/core/HazelcastJsonValue.ts
  src/core/Member.ts
  src/core/MembershipListener.ts
  src/core/PartitionAware.ts
  src/core/ReadResultSet.ts
  src/discovery/HazelcastCloudDiscovery.ts
  src/invocation/ClusterService.ts
  src/network/ConnectionManager.ts
  src/network/TranslateAddressProvider.ts
  src/proxy/FlakeIdGenerator.ts
  src/proxy/IAtomicReference.ts
  src/proxy/ICountDownLatch.ts
  src/proxy/IList.ts
  src/proxy/IMap.ts
  src/proxy/IQueue.ts
  src/proxy/ISet.ts
  src/proxy/ITopic.ts
  src/proxy/OverflowPolicy.ts
  src/proxy/PNCounter.ts
  src/proxy/ReplicatedMap.ts
  src/proxy/Ringbuffer.ts
  src/proxy/TopicOverloadPolicy.ts
  src/serialization/Serializable.ts
  src/util/IndexUtil.ts
Labels: Estimation: S, Priority: Medium, Type: Documentation

#813 Replace deprecated assert functions
  src/serialization/portable/ClassDefinition.ts
  src/util/Util.ts
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Enhancement

#802 Replace utf with string in public API
  DOCUMENTATION.md
  code_samples/global_serializer.js
  code_samples/identified_data_serializable.js
  code_samples/jaas_sample/hazelcast-member/src/main/java/com/company/security/UsernamePasswordCredentials.java
  code_samples/jaas_sample/user_pass_cred.js
  code_samples/org-website/GlobalSerializerSample.js
  code_samples/org-website/IdentifiedDataSerializableSample.js
  code_samples/org-website/PortableSerializableSample.js
  code_samples/org-website/QuerySample.js
  code_samples/portable_multiversion_sample.js
  src/aggregation/Aggregator.ts
  src/core/Address.ts
  src/core/RestValue.ts
  src/serialization/Data.ts
  src/serialization/DefaultPredicates.ts
  src/serialization/DefaultSerializers.ts
  src/serialization/ObjectData.ts
  src/serialization/Portable.ts
  src/serialization/portable/ClassDefinitionBuilder.ts
  src/serialization/portable/ClassDefinitionWriter.ts
  src/serialization/portable/DefaultPortableReader.ts
  src/serialization/portable/DefaultPortableWriter.ts
  src/serialization/portable/MorphingPortableReader.ts
  test/integration/javaclasses/DistortInvalidationMetadataEntryProcessor.js
  test/integration/javaclasses/IdentifiedEntryProcessor.js
  test/integration/javaclasses/PrefixFilter.js
  test/integration/serialization/Address.js
  test/integration/serialization/Foo.js
  test/soak_test/IdentifiedEntryProcessor.js
  test/unit/serialization/APortable.js
  test/unit/serialization/AnIdentifiedDataSerializable.js
  test/unit/serialization/CustomSerializerTest.js
  test/unit/serialization/GlobalSerializerTest.js
  test/unit/serialization/IdentifiedDataSerializableTest.js
  test/unit/serialization/ObjectDataTest.js
  test/unit/serialization/PortableObjects.js
Labels: Estimation: M, Priority: Low, Source: Internal, Type: Cleanup

#816 Bump typescript version to 4
  package.json
  src/aggregation/Aggregator.ts
  src/proxy/MapListener.ts
Labels: Estimation: S, Priority: Medium, Source: Internal, Type: Enhancement

#826 Properly log tried addresses when the client cannot connect to cluster
  src/network/ConnectionManager.ts
Labels: Source: Internal, Type: Cleanup

#823 Infinite reconnection attempts by default behaviour
  DOCUMENTATION.md
  src/config/ConfigBuilder.ts
  src/config/ConnectionRetryConfig.ts
  src/network/WaitStrategy.ts
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Enhancement

#825 Update dependencies
  package.json
Labels: Source: Internal

#827 Make dev dependency versions similar
  package.json
Labels: Estimation: S, Priority: Low, Source: Internal

#830 Add dependabot config yml
  .github/dependabot.yml
Labels: Estimation: S, Priority: Low, Source: Internal

#834 Fix typo in dependabot config
  .github/dependabot.yml
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Defect

#822 Change method of determining which files to publish
  .npmignore
  package.json
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Cleanup
