Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2022-10, with the labels that each got.

#1379 Fix leak in ReliableTopicListenerRunner.next API-1514
  src/proxy/topic/ReliableTopicListenerRunner.ts
Labels: Type: Defect, Backport

#1380 Fix leak in ReliableTopicListenerRunner.next API-1514
  src/proxy/topic/ReliableTopicListenerRunner.ts
Labels: Type: Defect, Backport

#1381 Fix leak in ReliableTopicListenerRunner.next API-1514
  src/proxy/topic/ReliableTopicListenerRunner.ts
Labels: Type: Defect, Backport

#1382 Fix leak in ReliableTopicListenerRunner.next API-1514
  src/proxy/topic/ReliableTopicListenerRunner.ts
Labels: Type: Defect

#1391 Add 5.2 version checks for the tests that are for map.removeAll
  package.json
  test/integration/backward_compatible/parallel/map/NearCachedMapTest.js
  test/integration/backward_compatible/parallel/serialization/compact/CompactPublicAPIsTest.js
  test/integration/backward_compatible/serial/map/MapProxyTest.js
Labels: Type: Test-Failure, Estimation: S, Source: Internal

#1398 Add skipped check before asserting in CompactPublicAPIsTest.afterEach
  test/integration/backward_compatible/parallel/serialization/compact/CompactPublicAPIsTest.js
Labels: Type: Test-Failure

#1403 Change doTryNextCluster logic to make it the same. [API-1354]
  src/ClusterFailoverService.ts
  test/unit/ClusterFailoverServiceTest.js
Labels: Type: Defect, Estimation: S, Source: Internal
