Repository hazelcast/hazelcast-nodejs-client, pull requests merged in 2022-12, with the labels that each got.

#1428 Update dependencies
  .mocharc.json
  CONTRIBUTING.md
  package.json
  src/HazelcastClient.ts
  src/config/SSLConfig.ts
  src/serialization/compact/CompactReader.ts
  src/serialization/generic_record/GenericRecords.ts
  src/util/Util.ts
Labels: dependencies

#1433 Document update for compact
  DOCUMENTATION.md
Labels: Type: Documentation, Source: Community

#1435 Fix backward compatibility test v5.2.0
  test/TestUtil.js
  test/integration/backward_compatible/parallel/map/NearCachedMapTest.js
  test/integration/backward_compatible/parallel/serialization/compact/CompactPublicAPIsTest.js
  test/integration/backward_compatible/parallel/serialization/compact/CompactSerializersLiveTest.js
  test/integration/backward_compatible/parallel/serialization/compact/CompactTest.js
  test/integration/backward_compatible/parallel/serialization/compact/PartitionServiceTest.js
  test/integration/backward_compatible/parallel/sql/DataTypeTest.js
  test/integration/backward_compatible/serial/CompactRestartTest.js
Labels: Type: Test-Failure, Source: Internal

#1436 Fix ssl test re-enabled
  .github/workflows/coverage_runner.yml
  .github/workflows/nightly_runner_master.yml
  scripts/download-rc.js
  scripts/test-runner.js
  test/integration/backward_compatible/parallel/ssl/ClientSSLAuthenticationTest.js
  test/integration/backward_compatible/parallel/ssl/ClientSSLTest.js
Labels: Type: Test-Failure, Source: Internal

#1441 Fix nightly runner workflow
  .github/workflows/nightly_runner_master.yml
Labels: Type: Test-Failure, Source: Internal

#1443 Fix coverage runner for windows
  .github/workflows/coverage_runner.yml
Labels: Type: Test-Failure, Source: Internal

#1442 Change logic around closing connections and writers API-1283 (redux)
  src/network/Connection.ts
  test/unit/connection/DirectWriterTest.js
  test/unit/connection/PipelinedWriterTest.js
Labels: Type: Test-Failure, Priority: High, Estimation: M, Source: Internal

#1446 Allow all branches in coverage runner
  .github/workflows/coverage_runner.yml
Labels: Type: Defect, Estimation: S, Source: Internal

#1447 Compact documentation update
  DOCUMENTATION.md
Labels: Type: Documentation, Forwardport, Source: Internal

#1431 New types added to binary compatibility test for Portable [API-1677]
  test/TestUtil.js
  test/unit/serialization/1.serialization.compatibility.binary
  test/unit/serialization/APortable.js
  test/unit/serialization/ReferenceObjects.java
  test/unit/serialization/ReferenceObjects.js
Labels: Type: Enhancement, Source: Internal

#1432 Logging does not work if written in lowercase(hazelcast.logging.level) [API-1740]
  DOCUMENTATION.md
  code_samples/logging_level_sample.js
  src/util/Util.ts
  test/unit/config/ConfigBuilderTest.js
  test/unit/discovery/HazelcastCloudProviderTest.js
Labels: Type: Defect, Source: Internal

#1444 Do not try to connect cluster members when the client is not connected to cluster [API-1588]
  test/TestUtil.js
  test/integration/backward_compatible/serial/ClientClusterReconnectionRetryTest.js
Labels: Type: Defect, Source: Internal

#1411 Check for the minimum size of the bytes read only once per frame [API-1546]
  test/unit/connection/ClientMessageReaderTest.js
Labels: Type: Enhancement, Source: Internal

#1451 Compact serialization codecov test results issues[API-1791]
  src/serialization/compact/DefaultCompactWriter.ts
  src/serialization/compact/Schema.ts
  src/serialization/generic_record/CompactGenericRecord.ts
  test/unit/serialization/compact/CompactTest.js
  test/unit/serialization/compact/SchemaTest.js
Labels: Type: Enhancement, Source: Internal

#1452 Don't allow empty memberlist on cluster id changes[API-1590]
  src/HazelcastClient.ts
  src/core/MembershipListener.ts
  src/invocation/ClusterService.ts
  src/listener/ClusterViewListenerService.ts
  src/network/Connection.ts
  src/network/ConnectionManager.ts
  test/unit/ClusterServiceTest.js
Labels: Type: Enhancement, Source: Internal
